#
# .zshrc is sourced in interactive shells.
# It should contain commands to set up aliases,
# functions, options, key bindings, etc.
#
# source profile like .bashrc

HISTFILE=~/.zsh_history
HISTSIZE=50000
SAVEHIST=10000
setopt appendhistory autocd extendedglob

if [ -f /etc/profile ]; then
	source /etc/profile
fi

# export EMAIL="Hiroyuki Nakamura <hryk@cpan.org>"
# export PATH='/usr/bin:/opt/local/bin/:/usr/local/graphviz-devel/bin/:/usr/local/bin:'$PATH
# export PYTHONPATH='/usr/local/lib/python2.5/site-packages:'$PYTHONPATH
# export SCREENDIR='/Users/hiroyuki/.screen'
export LANG="ja_JP.UTF-8"
export LC_ALL="ja_JP.UTF-8"
# export TERM="xterm-color"
# export QTDIR=/opt/local/lib/qt3

# export EC2_HOME=~/.ec2
# export PATH=$PATH:$EC2_HOME/bin:/opt/jruby/bin
# export EC2_PRIVATE_KEY=`ls $EC2_HOME/pk-*.pem`
# export EC2_CERT=`ls $EC2_HOME/cert-*.pem`
# export JAVA_HOME=/System/Library/Frameworks/JavaVM.framework/Home/
# export LSCOLORS=Exfxcxdxbxegedabagacad
#export DYLD_LIBRARY_PATH='/usr/local/lib:/opt/local/lib:/System/Library/Frameworks/JavaVM.framework/Home/shared_bundle/Versions/1.6.0/Libraries':$DYLD_LIBRARY_PATH

autoload -U compinit
compinit

setopt auto_cd
setopt auto_pushd
setopt correct
setopt multios
unsetopt promptcr

# alias -s txt=less
# alias -s xml=less
# alias df="df -h"
# alias ll="ls -lG"
# alias la="ls -aG"
# alias ls="ls -G"
# alias vi="/usr/local/bin/vim"
# alias vim="/usr/local/bin/vim"
# alias gvim="/Applications/Vim.app/Contents/MacOS/Vim -g"
# alias show="open -a Finder ."
# alias hg="python2.5 /usr/local/bin/hg --encoding=utf-8"

zstyle ':completion:*' verbose yes
zstyle ':completion:*:descriptions' format '%B%d%b'
zstyle ':completion:*:messages' format '%d'
zstyle ':completion:*:warnings' format 'No matches for: %d'
zstyle ':completion:*' group-name ''

local GREEN=$'%{\e[34m%}'
local BLUE=$'%{\e[35m%}'
local DEFAULT=$'%{\e[1;m%}'

autoload colors ; colors

PROMPT=$BLUE'[${USER}@${HOST}]%% '$DEFAULT
RPROMPT=$GREEN'[%~]'$DEFAULT
setopt PROMPT_SUBST
