# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="cloud_mine"

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git git-flow rails3 bundler cpanm osx rbenv notification)

source $ZSH/oh-my-zsh.sh

# Customize to your needs...

# Environment Variables
export PATH=/Users/hiroyuki/.rbenv/shims:/usr/local/narwhal/bin:/Users/hiroyuki/perl5/perlbrew/bin:/Users/hiroyuki/.rbenv/bin:/Users/hiroyuki/bin:/Users/hiroyuki/.bin:/usr/local/bin:/usr/local/sbin:/usr/local/share/npm/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/local/ncbi/blast/bin:/usr/X11/bin:/usr/local/narwhal/bin:/Users/hiroyuki/bin:/Users/hiroyuki/.bin:/usr/local/sbin:/usr/local/share/npm/bin
export LANG="ja_JP.UTF-8"
export LC_ALL="ja_JP.UTF-8"
export GISTY_DIR="$HOME/Develop/gists"
export GISTY_SSL_VERIFY="none"
export GISTY_ACCESS_TOKEN=""
export ANT_OPTS="$ANT_OPTS -Dfile.encoding=UTF8"
export NODE_PATH="/usr/local/lib/node_modules"
# Aliases
alias ll="ls -lG"
alias la="ls -aG"
alias ls="ls -G"
alias gvim="/Applications/Vim.app/Contents/MacOS/Vim -g"
alias show="open -a Finder ."
# Global aliases
alias -g V='| vim -R -' 
# notification configuration.
znotify[on_complete]='growlnotify -t "$command_name おわった" -m "今終わった.($formatted_elapsed_timeかかった.)"'
znotify[ignore]="vim ssh man less top htop emacs builtin tmux"
znotify[threshold]=60
