# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
# ZSH_THEME="cloud_mine"
ZSH_THEME="hiroyuki"

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git git-flow rails bundler cpanm osx rbenv notification nova perl go colorize vagrant node aws)

source $ZSH/oh-my-zsh.sh

# Customize to your needs...

autoload -U bashcompinit
autoload -U compinit

# Environment Variables

## PATH
export PATH="$HOME/.cabal/bin:$PATH"
export PATH="/usr/local/narwhal/bin:$PATH"
export PATH="$HOME/perl5/perlbrew/bin:$PATH"
export PATH="$HOME/bin:$PATH"
export PATH="/usr/local/bin:/usr/local/sbin:/usr/local/share/npm/bin:/usr/local/opt/coreutils/libexec/gnubin:$PATH"
export PATH="/usr/local/ncbi/blast/bin:$PATH"
export PATH="/usr/local/heroku/bin:$PATH"
export PATH="/usr/X11/bin:$PATH"
export PATH="$HOME/gocode/bin:$PATH"
export PATH="$HOME/miniconda3/bin:$PATH"
export PATH=$PATH:/usr/local/opt/go/libexec/bin
export PATH="$HOME/.rbenv/shims:$HOME/.rbenv/bin:$PATH"

export LANG="ja_JP.UTF-8"
export LC_ALL="ja_JP.UTF-8"

export NODE_PATH="/usr/local/lib/node_modules"
export NODE_PATH="/usr/local/lib/jsctags:$NODE_PATH"
export RUBYLIB="$HOME/.puppet/modules/node_openstack/lib:$HOME/.puppet/modules/cloud_provisioner/lib"
export GOPATH="$HOME/gocode"
export MANPATH="/usr/local/opt/coreutils/libexec/gnuman:$MANPATH"

export ANDROID_HOME="/usr/local/opt/android-sdk"
export ANT_OPTS="$ANT_OPTS -Dfile.encoding=UTF8"
export GISTY_DIR="$HOME/Develop/gists"
export GISTY_SSL_VERIFY="none"
export GISTY_ACCESS_TOKEN="4121d1e605c2677bb3ee6052c1a3f441b7742eb5"

export WORQUE_PATH="$HOME/Dropbox/Documents/Todo"
alias today="vim $(worque todo) +':cd $WORQUE_PATH'"

# Aliases
alias ll="gls -l --color"
alias la="gls -a --color"
alias ls="gls --color"
alias gvim="/Applications/Vim.app/Contents/MacOS/Vim -g"
alias show="open -a Finder ."
alias ack="ag"
alias diff="colordiff"
alias less="less -R"
alias node="node --harmony"

# Global aliases
alias -g V='| vim -R -'
alias zmv='noglob zmv -W '

# Antha
alias manrun='antharun --workflow workflow.json --parameters parameters.yml --driver localhost:50051'
alias workflows='cd $GOPATH/src/github.com/antha-lang/antha/antha/examples/workflows'
alias anthapath='cd $GOPATH/src/github.com/antha-lang/antha'

# notification configuration.
znotify[on_complete]='growlnotify -t "$command_name おわった" -m "終わった. ($formatted_elapsed_timeかかった.)"'
znotify[ignore]="vim ssh man less top htop emacs builtin tmux"
znotify[threshold]=60

# z
. `brew --prefix`/etc/profile.d/z.sh

# completions

fpath=(/usr/local/share/zsh/site-functions/ $fpath)
fpath=($HOME/.oh-my-zsh/custom/zsh-completions/src $fpath)

### Brewed ssh-agent
export SSH_AUTH_SOCK=$(launchctl getenv SSH_AUTH_SOCK)
eval $(ssh-agent)

function cleanup {
  echo "Killing SSH-Agent"
  kill -9 $SSH_AGENT_PID
}

trap cleanup EXIT
